services:
  - type: web
    name: axiom-id-web-api
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npx lerna bootstrap
    startCommand: npm run web-api --workspace=axiom-assist-bot
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false

  - type: web
    name: axiom-id-socket-server
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npx lerna bootstrap
    startCommand: npm run socket:start --workspace=axiom-assist-bot
    domains:
      - api.axiomid.app
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SOCKET_PORT
        value: 3001
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: WEB_API_INTERNAL_URL
        value: http://axiom-id-web-api:3000

