[features]
resolution = true
skip-lint = false

[programs.localnet]
axiom_id = "5E7eosX9X34CWCeGpw2C4ua2JRYTZqZ8MsFkxj3y6T7C"
agent_soul_factory = "6sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_attestations = "4sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_staking = "3sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_token = "7sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_governance = "8sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_pohw = "9sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_staking_dynamic = "AsKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"

[programs.devnet]
axiom_id = "5E7eosX9X34CWCeGpw2C4ua2JRYTZqZ8MsFkxj3y6T7C"
agent_soul_factory = "6sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_attestations = "4sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_staking = "3sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_token = "7sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_governance = "8sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_pohw = "9sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_staking_dynamic = "AsKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"

[programs.mainnet]
axiom_id = "5E7eosX9X34CWCeGpw2C4ua2JRYTZqZ8MsFkxj3y6T7C"
agent_soul_factory = "6sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_attestations = "4sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_staking = "3sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_token = "7sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_governance = "8sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_pohw = "9sKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"
axiom_staking_dynamic = "AsKxhfHdQgjWBuoztEYonKepba2zGcN2QtWowCmAfWzD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"