[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.bpfel-unknown-none]
linker = "rust-lld"
rustflags = ["-C", "link-arg=-zmax-page-size=0x1000"]